apiVersion: v1
kind: Service
metadata:
  name: payment-postgres-headless
  namespace: payment-postgres
  labels:
    app.kubernetes.io/name: payment-postgres
    app.kubernetes.io/component: database-headless
spec:
  type: ClusterIP
  clusterIP: None # Headless — DNS langsung mengembalikan IP Pod (wajib untuk StatefulSet)
  selector:
    app: payment-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: payment-postgres
  namespace: payment-postgres
  labels:
    app.kubernetes.io/name: payment-postgres
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app: payment-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
